#исключение
try:
   num1 = 7
   num2 = 0
   print (num1 / num2)
   print("Done calculation")
except ZeroDivisionError:
   print("An error occurred")
   print("due to zero division")

#несколько вариантов действия
try:
   variable = 10
   print(variable + "hello")
   print(variable / 2)
except ZeroDivisionError:
   print("Divided by zero")
except (ValueError, TypeError):
   print("Error occurred")

#блок finally выполняется всегда
try:
   print(1 / 0)
except ZeroDivisionError:
   print("Divided by zero")
finally:
   print("This code will run no matter what")

#вызов исключения
#raise ValueError
#raise NameError("Invalid name!")
#try:
#повторный вызов исключения
#   num = 5 / 0
#except:
#   print("An error occurred")
#   raise
